project_info:
  project_name: "Default Project"
  project_description: "This is a default project."

component_selection:
  solar_pv: true
  wind: true
  generator: true
  battery: true
  technical_validation: true
  economic_validation: false
  energy_balance: true
  conversion: false

solar_pv_parameters:
    solar_pv_num_units: 4
    same_date: false
    installation_dates: [2022-01-01 00:00:00, 2027-01-01 00:00:00, 2027-01-01 00:00:00, 2027-01-01 00:00:00]
    num_solar_pv_types: 4
    same_type: false
    solar_pv_types: ['Type 1', 'Type 2', 'Type 3', 'Type 4']
    solar_pv_type: ['Type 1', 'Type 2', 'Type 3', 'Type 4']
    pv_lifetime: [20, 20, 20, 20]
    pv_rho: 0.2
    solar_pv_calculation_type: ['Nominal Power', 'Nominal Power', 'Nominal Power', 'Nominal Power']
    pv_area: [5.0, 5.0, 5.0, 5.0]
    pv_efficiency: [20.0, 20.0, 20.0, 20.0]
    pv_nominal_power: [450.0, 450.0, 450.0, 450.0]
    pv_theta_tilt: [10.0, 10.0, 10.0, 10.0]
    pv_azimuth: [180.0, 180.0, 180.0, 180.0]
    pv_degradation: false
    pv_degradation_rate: [0, 0, 0, 0]
    pv_temperature_dependent_efficiency: true
    pv_temperature_coefficient: [-0.37, -0.37, -0.37, -0.37]
    pv_T_ref: [25.0, 25.0, 25.0, 25.0]
    pv_T_ref_NOCT: [20.0, 20.0, 20.0, 20.0]
    pv_NOCT: [45.0, 45.0, 45.0, 45.0]
    pv_I_ref_NOCT: [800.0, 800.0, 800.0, 800.0]
    pv_dynamic_inverter_efficiency: false
    pv_inverter_efficiency: [100.0, 100.0, 100.0, 100.0]
    solar_pv_investment_cost: [0.0, 0.0, 0.0, 0.0]
    solar_pv_exclude_investment_cost: [False, False, False, False]
    solar_pv_maintenance_cost: [0.0, 0.0, 0.0, 0.0]
    solar_pv_end_of_project_cost: [0.0, 0.0, 0.0, 0.0]
    solar_pv_curtailment: [true, true, true, true]
    
solar_irradiation_parameters:
    solar_irradiation_selected_input_type: "GHI & DHI"
    solar_irradiation_delimiter: "Comma (,)"
    solar_irradiation_decimal: "Dot (.)"
    solar_irradiation_time_format: "%d/%m/%Y %H:%M"
    irradiation_data_uploaded: false
    Input_GHI: false
    Input_DHI: false
    Input_DNI: false
    Input_G_total: false
    solar_irradiation_data_source: "Download from PVGIS"
    albedo: false
    albedo_coefficient: 20.0

battery_parameters:
    battery_num_units: 4
    battery_installation_dates: [2022-01-01 00:00:00, 2027-01-01 00:00:00, 2032-01-01 00:00:00, 2037-01-01 00:00:00]
    num_battery_types: 4
    battery_same_date: false
    battery_same_type: false
    battery_types: ['Type 1', 'Type 2', 'Type 3', 'Type 4']
    battery_type: ['Type 1', 'Type 2', 'Type 3', 'Type 4']
    battery_temporal_degradation: false
    battery_cyclic_degradation: true
    battery_dynamic_inverter_efficiency: false
    battery_capacity: [5000.0]
    battery_lifetime: [20]
    battery_charging_efficiency: [90.0, 90.0, 90.0, 90.0]
    battery_discharging_efficiency: [90.0, 90.0, 90.0, 90.0]
    battery_roundtrip_efficiency: [90.0]
    battery_initial_soc: [100.0]
    battery_min_soc: [20.0]
    battery_max_soc: [100.0]
    battery_max_charge_power: [500.0]
    battery_max_discharge_power: [500.0]
    battery_min_charge_time: [5]
    battery_min_discharge_time: [4]
    battery_inverter_efficiency: [100.0]
    battery_efficiency_type: 'Seperate Charging and Discharging Efficiency'
    battery_inverter_eff_included: [true, true, true, true]
    battery_temporal_degradation_rate: [2.0, 2.0, 2.0, 2.0]
    battery_investment_cost: [0.0, 0.0, 0.0, 0.0]
    battery_exclude_investment_cost: [False, False, False, False]
    battery_maintenance_cost: [0.0, 0.0, 0.0, 0.0]
    battery_end_of_project_cost: [0.0, 0.0, 0.0, 0.0]
    battery_chemistry: ['LFP - Lithium Iron Phosphate (LFP)']
    battery_model: ['Lfp_Gr_250AhPrismatic']
    battery_degradation_accounting: "Salvage Value"

wind_parameters:
    wind_num_units: 4
    wind_installation_dates: [2022-01-01 00:00:00, 2027-01-01 00:00:00, 2032-01-01 00:00:00, 2037-01-01 00:00:00]
    wind_installation_dates_utc: [2021-12-31 22:00:00, 2026-12-31 22:00:00, 2031-12-31 22:00:00, 2036-12-31 22:00:00]
    wind_same_date: false
    wind_types: ['Type 1', 'Type 2', 'Type 3', 'Type 4']
    wind_type: ['Type 1', 'Type 2', 'Type 3', 'Type 4']
    wind_same_type: false
    num_wind_types: 4
    wind_turbine_type: ["Horizontal", "Horizontal", "Horizontal", "Horizontal"]
    wind_lifetime: [20, 20, 20, 20]
    wind_rated_power: [500.0, 500.0, 500.0, 500.0]
    wind_drivetrain_efficiency: [90.0, 90.0, 90.0, 90.0]
    wind_diameter: [20.7, 20.7, 20.7, 20.7]
    wind_hub_height: [37.00, 37.00, 37.00, 37.00]
    wind_power_curve_uploaded: [false]
    wind_temporal_degradation: false
    wind_temporal_degradation_rate: [1.0, 1.0, 1.0, 1.0]
    wind_speed_data_uploaded: false
    wind_selected_input_type: "Wind Speed given for one Height"
    wind_Z1: 50.0
    wind_Z0: 10.0
    wind_surface_type: "Suburbs"
    wind_surface_roughness: 1.50
    wind_investment_cost: [0.0, 0.0, 0.0, 0.0]
    wind_exclude_investment_cost: [False, False, False, False]
    wind_maintenance_cost: [0.0, 0.0, 0.0, 0.0]
    wind_end_of_project_cost: [0.0, 0.0, 0.0, 0.0]
    wind_curtailment: [true, true, true, true]

generator_parameters:
    generator_num_units: 5
    generator_installation_dates: [2017-01-01 00:00:00, 2022-01-01 00:00:00, 2027-01-01 00:00:00, 2032-01-01 00:00:00, 2037-01-01 00:00:00]
    generator_installation_dates_utc: [2016-12-31 22:00:00, 2021-12-31 22:00:00, 2026-12-31 22:00:00, 2031-12-31 22:00:00, 2036-12-31 22:00:00]
    generator_same_date: false
    num_generator_types: 5
    generator_types: ['Type 1', 'Type 2', 'Type 3', 'Type 4', 'Type 5']
    generator_type: ['Type 1', 'Type 2', 'Type 3', 'Type 4', 'Type 5']
    generator_same_type: false
    generator_dynamic_efficiency: false
    generator_temporal_degradation: false
    generator_cyclic_degradation: false
    generator_efficiency: [30.0, 30.0, 30.0, 30.0]
    generator_lifetime: [20, 20, 20, 20]
    generator_min_power: [0.0, 0.0, 0.0, 0.0]
    generator_max_power: [450.0, 450.0, 450.0, 450.0]
    generator_fuel_lhv: [10140.0, 10140.0, 10140.0, 10140.0]
    generator_temporal_degradation_rate: [1.0, 1.0, 1.0, 1.0]
    generator_dynamic_efficiency_type: ["Tabular Data", "Tabular Data", "Tabular Data", "Tabular Data"]
    generator_dynamic_efficiency_uploaded: [false, false, false, false]
    generator_efficiency_formula: [false, false, false, false]
    generator_fuel_consumption_scope: ["Total", "Total", "Total", "Total"]
    generator_total_fuel_consumption: [1000.0, 1000.0, 1000.0, 1000.0]
    generator_investment_cost: [0.0, 0.0, 0.0, 0.0]
    generator_exclude_investment_cost: [True, False, False, False]
    generator_maintenance_cost: [0.0, 0.0, 0.0, 0.0]
    generator_end_of_project_cost: [0.0, 0.0, 0.0, 0.0]
    generator_fuel_price: 1.80
    generator_variable_fuel_price: false
    generator_variable_fuel_price_uploaded: false

conversion_parameters:
    solar_pv_conversion_efficiency: 100.0
    solar_pv_connection_type: "Connected directly to the Microgrid"
    wind_conversion_efficiency: 100.0
    wind_connection_type: "Connected directly to the Microgrid"
    generator_conversion_efficiency: 100.0
    battery_conversion_efficiency_ac_dc: 95.0
    battery_conversion_efficiency_dc_ac: 95.0
    conversion_losses_data_uploaded: false

upload_model_parameters:
    solar_pv_data_uploaded: false
    solar_pv_model_output_scope: "Total"
    battery_data_uploaded: false
    battery_model_output_scope: "Total"
    wind_data_uploaded: false
    wind_model_output_scope: "Total"
    generator_data_uploaded: false
    generator_model_output_scope: "Total"
    wind_data_uploaded: false
    wind_model_output_scope: "Total"
    consumption_data_uploaded: false
    consumption_model_output_scope: "Total"

general_info:
  start_date: "2021-12-31 22:00:00"
  end_date: "2041-12-31 21:00:00"
  timezone: "Etc/GMT-2"
  discount_rate: 5.0
  lat: 2.06
  lon: 41.11
  current_type: "Alternating Current"

generate_plots:
  plots_generated: false