project_info:
  project_name: "Default Project"
  project_description: "This is a default project."

component_selection:
  solar_pv: true
  wind: false
  generator: false
  battery: false

solar_pv_parameters:
    solar_pv_num_units: 1
    same_date: true
    selected_timezone_solar_pv: "Universal Time Coordinated - UTC"
    installation_dates: [2024-01-01 00:00:00]
    installation_dates_utc: [2024-01-01 00:00:00]
    num_solar_pv_types: 1
    same_type: true
    solar_pv_types: ['Type 1']
    solar_pv_type: ['Type 1']
    pv_lifetime: [20]
    pv_area: [5.0]
    pv_efficiency: [20.0]
    pv_theta_tilt: [0.3]
    pv_degradation: false
    pv_degradation_rate: [0.5]
    pv_temperature_dependent_efficiency: false
    pv_temperature_coefficient: [0.5]
    pv_T_ref: [25.0]
    pv_T_ref_NOCT: [25.0]
    pv_NOCT: [45.0]
    pv_I_ref_NOCT: [1000.0]
    pv_albedo: false
    pv_albedo_coefficient: 0.2
    pv_dynamic_inverter_efficiency: false
    pv_inverter_efficiency: [80.0]
    
solar_irradiation_parameters:
    solar_irradiation_selected_input_type: "GHI & DHI"
    solar_irradiation_delimiter: "Comma (,)"
    solar_irradiation_decimal: "Dot (.)"
    solar_irradiation_time_format: "%d/%m/%Y %H:%M"
    solar_irradiation_timezone: "Universal Time Coordinated - UTC"
    irradiation_data_uploaded: false
    Input_GHI: false
    Input_DHI: false
    Input_DNI: false
    Input_G_total: false
    solar_irradiation_data_source: "Upload your own data"
    albedo: false
    albedo_coefficient: 20.0
    selected_timezone_solar_irradiation: "UTC"

battery_parameters:
    battery_num_units: 1
    battery_installation_dates: [2024-01-01 00:00:00]
    battery_installation_dates_utc: [2024-01-01 00:00:00]
    battery_same_date: true
    selected_timezone_battery: "Universal Time Coordinated - UTC"
    battery_same_type: true
    battery_types: ['Type 1']
    battery_type: ['Type 1']
    battery_temporal_degradation: false
    battery_cyclic_degradation: false
    battery_dynamic_inverter_efficiency: false
    battery_capacity: [5000.0]
    battery_lifetime: [20]
    battery_charging_efficiency: [95.0]
    battery_discharging_efficiency: [95.0]
    battery_roundtrip_efficiency: [90.0]
    battery_initial_soc: [60.0]
    battery_min_soc: [10.0]
    battery_max_soc: [100.0]
    battery_max_charge_power: [500.0]
    battery_max_discharge_power: [500.0]
    battery_inverter_efficiency: [90.0]
    battery_efficiency_type: 'Seperate Charging and Discharging Efficiency'
    battery_inverter_eff_included: [true]
    battery_temporal_degradation_rate: [2.0]

wind_parameters:
    wind_num_units: 1
    wind_installation_dates: [2024-01-01 00:00:00]
    wind_installation_dates_utc: [2024-01-01 00:00:00]
    wind_same_date: true
    selected_timezone_wind: "Universal Time Coordinated - UTC"
    wind_types: ['Type 1']
    wind_type: ['Type 1']
    wind_same_type: true
    wind_turbine_type: ["Horizontal"]
    wind_lifetime: [20]
    wind_rated_power: [500.0]
    wind_efficiency: [90.0]
    wind_diameter: [1.00]
    wind_hub_height: [1.00]
    wind_power_curve_uploaded: [false]
    wind_temporal_degradation: false
    wind_temporal_degradation_rate: [1.0]
    wind_speed_data_uploaded: false
    wind_selected_input_type: "Two Wind Speed Heights given"
    wind_Z1: 50.0
    wind_Z0: 10.0
    wind_surface_type: "Suburbs"
    wind_surface_roughness: 1.50

generator_parameters:
    generator_num_units: 1
    generator_installation_dates: [2024-01-01 00:00:00]
    generator_installation_dates_utc: [2024-01-01 00:00:00]
    generator_same_date: true
    selected_timezone_generator: "Universal Time Coordinated - UTC"
    generator_types: ['Type 1']
    generator_type: ['Type 1']
    generator_same_type: true
    generator_dynamic_efficiency: false
    generator_temporal_degradation: false
    generator_cyclic_degradation: false
    generator_efficiency: [30.0]
    generator_lifetime: [20]
    generator_min_power: [2.0]
    generator_max_power: [20.0]
    generator_fuel_lhv: [10140.0]
    generator_temporal_degradation_rate: [1.0]
    generator_dynamic_efficiency_type: ["Tabular Data"]
    generator_dynamic_efficiency_uploaded: [false]
    generator_efficiency_formula: [false]

upload_model_parameters:
    solar_pv_data_uploaded: false
    solar_pv_model_output_scope: "Total"
    battery_data_uploaded: false
    battery_model_output_scope: "Total"
    wind_data_uploaded: false
    wind_model_output_scope: "Total"
    generator_data_uploaded: false
    generator_model_output_scope: "Total"
    wind_data_uploaded: false
    wind_model_output_scope: "Total"

general_info:
  start_date: "2024-01-01 00:00:00"
  end_date: "2024-12-31 23:00:00"
  location: "Nairobi, Kenya"
  lat: 0.0
  lon: 0.0

generate_plots:
  plots_generated: false