project_info:
  project_name: "Default Project"
  project_description: "This is a default project."

component_selection:
  solar_pv: false
  wind: false
  generator: false
  battery: false

solar_pv_parameters:
    solar_pv_num_units: 1
    same_date: true
    selected_timezone_solar_pv: "Universal Time Coordinated - UTC"
    installation_dates: []
    installation_dates_utc: []
    num_solar_pv_types: 1
    same_type: true
    solar_pv_types: ['Type 1']
    solar_pv_type: ['Type 1']
    pv_lifetime: [20]
    pv_area: [5.0]
    pv_efficiency: [20.0]
    pv_theta_tilt: [0.3]
    pv_degradation: false
    pv_degradation_rate: [0.5]
    pv_temperature_dependent_efficiency: false
    pv_temperature_coefficient: [0.5]
    pv_T_ref: [25.0]
    pv_T_ref_NOCT: [25.0]
    pv_NOCT: [45.0]
    pv_I_ref_NOCT: [1000.0]
    pv_albedo: false
    pv_albedo_coefficient: 0.2
    pv_dynamic_inverter_efficiency: false
    pv_inverter_efficiency: [80.0]
    
solar_irradiation_parameters:
    solar_irradiation_selected_input_type: "GHI & DHI"
    solar_irradiation_delimiter: "Comma (,)"
    solar_irradiation_decimal: "Dot (.)"
    solar_irradiation_time_format: "%d/%m/%Y %H:%M"
    solar_irradiation_timezone: "Universal Time Coordinated - UTC"
    irradiation_data_uploaded: false
    Input_GHI: false
    Input_DHI: false
    Input_DNI: false
    Input_G_total: false
    solar_irradiation_data_source: "Upload your own data"
    albedo: false
    albedo_coefficient: 20.0
    selected_timezone_solar_irradiation: "UTC"

battery_parameters:
    battery_num_units: 1
    battery_installation_dates: []
    battery_installation_dates_utc: []
    battery_same_date: true
    selected_timezone_battery: str
    battery_same_type: true
    battery_types: []
    battery_type: []
    battery_temporal_degradation: false
    battery_cyclic_degradation: false
    battery_dynamic_inverter_efficiency: false
    battery_capacity: [5000.0]
    battery_lifetime: [20]
    battery_charging_efficiency: [95.0]
    battery_discharging_efficiency: [95.0]
    battery_initial_soc: [60.0]
    battery_min_soc: [10.0]
    battery_max_soc: [100.0]
    battery_max_charge_power: [500.0]
    battery_max_discharge_power: [500.0]
    battery_inverter_efficiency: [90.0]

upload_model_parameters:
    solar_pv_data_uploaded: false
    solar_pv_model_output_scope: "Total"
    battery_data_uploaded: false
    battery_model_output_scope: "Total"

general_info:
  start_date: "2024-01-01 00:00:00"
  end_date: "2024-12-31 23:00:00"
  location: "Nairobi, Kenya"
  lat: 0.0
  lon: 0.0

generate_plots:
  plots_generated: false